name: Run OCR Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1 libglib2.0-0

      - name: Set up virtual environment and install local package
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install openfilter"[all]" pytest
          cd openfilter && make install

      - name: Run pipeline (90s timeout)
        run: |
          timeout 90s python openfilter/examples/hello-world/pipeline_runner.py || echo "Pipeline finished or timed out"