name: Run OCR Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      OPENLINEAGE_URL: http://localhost:5000/api/v1/namespaces/default/jobs/dummy-job-name/runs/dummy-run-id # Exemplo de URL dummy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create virtualenv and install dependencies
        run: |
          pip install --upgrade pip
          pip install openfilter'[all]'
          python -m venv .venv
          source .venv/bin/activate
          (cd openfilter && make install)

      - name: Run pipeline with timeout
        run: |
          python -m venv .venv
          source .venv/bin/activate
          (cd openfilter && make install)
          export PYTHONPATH=$PYTHONPATH:$(pwd)/openfilter/examples 
          timeout 90s python openfilter/examples/hello-world/pipeline_runner.py || echo "Pipeline finished or timed out" 

      - name: Debug current directory and PYTHONPATH
        run: |
          pwd
          ls -R
          echo "PYTHONPATH: $PYTHONPATH"