name: Run OCR Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'openfilter/**'
      - 'ocr-filter/**'
      - '.github/workflows/run-pipeline.yaml'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'openfilter/**'
      - 'ocr-filter/**'
      - '.github/workflows/run-pipeline.yaml'

jobs:
  run-openfilter-pipeline:
    timeout-minutes: 10
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      OPENLINEAGE_DISABLED: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (openfilter)
        run: |
          cd openfilter
          pip install poetry
          poetry install --no-root
        shell: bash

      - name: Run OpenFilter pipeline
        run: |
          cd openfilter
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          timeout 30s poetry run python examples/hello-world/pipeline_runner.py || echo "Pipeline finished or timed out"
        shell: bash

  run-ocr-filter-pipeline:
    timeout-minutes: 10
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      OPENLINEAGE_DISABLED: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (ocr-filter)
        run: |
          cd ocr-filter
          pip install poetry
          poetry install --no-root
        shell: bash

      - name: Run OCR tests
        run: |
          cd ocr-filter
          poetry run pytest || echo "Tests completed with errors"
        shell: bash

      - name: Run OCR pipeline
        run: |
          cd ocr-filter
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          timeout 30s poetry run python pipeline_runner.py || echo "OCR pipeline finished or timed out"
        shell: bash