name: Run OCR Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up virtualenv and install project
        run: |
          python -m venv .venv
          source .venv/bin/activate
          cd openfilter
          make install

      - name: Run pipeline with timeout
        run: |
          cd .. 
          source .venv/bin/activate # Agora ative o virtualenv que está na raiz
          python openfilter/examples/hello-world/pipeline_runner.py || echo "Pipeline finished or timed out"
